FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    libopencv-dev\
    python3-opencv\
    libeigen3-dev\
    libyaml-cpp-dev\
 && rm -rf /var/lib/apt/lists/*
WORKDIR /RADAR-LOCATION-CAMERA
CMD ["/bin/bash"]
                    